# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_10_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name9',
        ),
    ]
